// src/app/sitemap.ts — all converted routes (generated from HTML build inventory)
import type { MetadataRoute } from 'next'
import { COMPANY } from '@/lib/constants'

const ROUTES: string[] = [
  "/",
  "/about",
  "/blog",
  "/blog/ai-automation-guide-indian-businesses-2026",
  "/blog/business-website-guide-india-2026",
  "/blog/seo-guide-indian-businesses-2026",
  "/careers",
  "/contact",
  "/honest",
  "/how-we-work",
  "/industries/automotive",
  "/industries/ecommerce",
  "/industries/education",
  "/industries/finance",
  "/industries/healthcare",
  "/industries/hospitality",
  "/industries/it-saas",
  "/industries/legal",
  "/industries/manufacturing",
  "/industries/real-estate",
  "/industries/restaurants",
  "/internship",
  "/legal/cookie-policy",
  "/legal/privacy",
  "/legal/terms",
  "/locations/bhopal/ai-automation",
  "/locations/bhopal/digital-marketing",
  "/locations/bhopal/ecommerce-development",
  "/locations/bhopal/ecommerce-seo",
  "/locations/bhopal/google-ads",
  "/locations/bhopal/link-building",
  "/locations/bhopal/local-seo",
  "/locations/bhopal/meta-ads",
  "/locations/bhopal/seo",
  "/locations/bhopal/social-media-marketing",
  "/locations/bhopal/technical-seo-audit",
  "/locations/bhopal/web-development",
  "/locations/bhopal/whatsapp-automation",
  "/locations/bhopal/wordpress-development",
  "/locations/indore/ai-automation",
  "/locations/indore/digital-marketing",
  "/locations/indore/ecommerce-development",
  "/locations/indore/ecommerce-seo",
  "/locations/indore/google-ads",
  "/locations/indore/link-building",
  "/locations/indore/local-seo",
  "/locations/indore/meta-ads",
  "/locations/indore/seo",
  "/locations/indore/social-media-marketing",
  "/locations/indore/technical-seo-audit",
  "/locations/indore/web-development",
  "/locations/indore/whatsapp-automation",
  "/locations/indore/wordpress-development",
  "/our-work",
  "/pricing",
  "/service-areas",
  "/services/ai-ad-creatives",
  "/services/ai-automation",
  "/services/ai-brand-visibility",
  "/services/ai-chatbot-development",
  "/services/ai-content",
  "/services/ai-search-optimization",
  "/services/ai-video",
  "/services/answer-engine-optimization",
  "/services/blogging",
  "/services/drone-video",
  "/services/ecommerce-development",
  "/services/ecommerce-seo",
  "/services/email-marketing",
  "/services/generative-engine-optimization",
  "/services/gmb-marketing",
  "/services/google-ads",
  "/services/google-trusted-photography",
  "/services/hd-photography",
  "/services/influencer-video",
  "/services/landing-pages",
  "/services/link-building",
  "/services/linkedin-ads",
  "/services/local-seo",
  "/services/meta-ads",
  "/services/product-photography",
  "/services/programmatic-seo",
  "/services/retargeting",
  "/services/seo",
  "/services/shopping-ads",
  "/services/technical-seo-audit",
  "/services/ui-ux",
  "/services/virtual-tour",
  "/services/web-development",
  "/services/whatsapp-automation",
  "/services/whatsapp-marketing",
  "/services/wordpress-development",
  "/services/workflow-automation",
  "/services/youtube-ads",
  "/site-map",
  "/white-label/ai",
  "/white-label/geo",
  "/white-label/ppc",
  "/white-label/reporting",
  "/white-label/seo",
  "/white-label/web-development"
]

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date()
  return ROUTES.map((path) => ({
    url: `${COMPANY.siteUrl}${path === '/' ? '' : path}`,
    lastModified: now,
    changeFrequency: path === '/' ? 'weekly' : 'monthly',
    priority: path === '/' ? 1 : path.startsWith('/blog') ? 0.7 : 0.8,
  }))
}
